// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/proto/customer.proto

package customer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RoleType int32

const (
	Role_worker  RoleType = 0
	Role_console RoleType = 1
)

var RoleType_name = map[int32]string{
	0: "worker",
	1: "console",
}

var RoleType_value = map[string]int32{
	"worker":  0,
	"console": 1,
}

func (x RoleType) String() string {
	return proto.EnumName(RoleType_name, int32(x))
}

func (RoleType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_09fdc6f199145f27, []int{4, 0}
}

// Request message for creating a new customer
type CustomerRequest struct {
	Id                   int32                      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string                     `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string                     `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Addresses            []*CustomerRequest_Address `protobuf:"bytes,5,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CustomerRequest) Reset()         { *m = CustomerRequest{} }
func (m *CustomerRequest) String() string { return proto.CompactTextString(m) }
func (*CustomerRequest) ProtoMessage()    {}
func (*CustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_09fdc6f199145f27, []int{0}
}

func (m *CustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerRequest.Unmarshal(m, b)
}
func (m *CustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerRequest.Marshal(b, m, deterministic)
}
func (m *CustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerRequest.Merge(m, src)
}
func (m *CustomerRequest) XXX_Size() int {
	return xxx_messageInfo_CustomerRequest.Size(m)
}
func (m *CustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerRequest proto.InternalMessageInfo

func (m *CustomerRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CustomerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CustomerRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CustomerRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CustomerRequest) GetAddresses() []*CustomerRequest_Address {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type CustomerRequest_Address struct {
	Street               string   `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City                 string   `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State                string   `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Zip                  string   `protobuf:"bytes,4,opt,name=zip,proto3" json:"zip,omitempty"`
	IsShippingAddress    bool     `protobuf:"varint,5,opt,name=isShippingAddress,proto3" json:"isShippingAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomerRequest_Address) Reset()         { *m = CustomerRequest_Address{} }
func (m *CustomerRequest_Address) String() string { return proto.CompactTextString(m) }
func (*CustomerRequest_Address) ProtoMessage()    {}
func (*CustomerRequest_Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_09fdc6f199145f27, []int{0, 0}
}

func (m *CustomerRequest_Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerRequest_Address.Unmarshal(m, b)
}
func (m *CustomerRequest_Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerRequest_Address.Marshal(b, m, deterministic)
}
func (m *CustomerRequest_Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerRequest_Address.Merge(m, src)
}
func (m *CustomerRequest_Address) XXX_Size() int {
	return xxx_messageInfo_CustomerRequest_Address.Size(m)
}
func (m *CustomerRequest_Address) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerRequest_Address.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerRequest_Address proto.InternalMessageInfo

func (m *CustomerRequest_Address) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *CustomerRequest_Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *CustomerRequest_Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *CustomerRequest_Address) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *CustomerRequest_Address) GetIsShippingAddress() bool {
	if m != nil {
		return m.IsShippingAddress
	}
	return false
}

type CustomerResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomerResponse) Reset()         { *m = CustomerResponse{} }
func (m *CustomerResponse) String() string { return proto.CompactTextString(m) }
func (*CustomerResponse) ProtoMessage()    {}
func (*CustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_09fdc6f199145f27, []int{1}
}

func (m *CustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerResponse.Unmarshal(m, b)
}
func (m *CustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerResponse.Marshal(b, m, deterministic)
}
func (m *CustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerResponse.Merge(m, src)
}
func (m *CustomerResponse) XXX_Size() int {
	return xxx_messageInfo_CustomerResponse.Size(m)
}
func (m *CustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerResponse proto.InternalMessageInfo

func (m *CustomerResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CustomerResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type CustomerFilter struct {
	Keyword              string   `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomerFilter) Reset()         { *m = CustomerFilter{} }
func (m *CustomerFilter) String() string { return proto.CompactTextString(m) }
func (*CustomerFilter) ProtoMessage()    {}
func (*CustomerFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_09fdc6f199145f27, []int{2}
}

func (m *CustomerFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerFilter.Unmarshal(m, b)
}
func (m *CustomerFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerFilter.Marshal(b, m, deterministic)
}
func (m *CustomerFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerFilter.Merge(m, src)
}
func (m *CustomerFilter) XXX_Size() int {
	return xxx_messageInfo_CustomerFilter.Size(m)
}
func (m *CustomerFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerFilter.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerFilter proto.InternalMessageInfo

func (m *CustomerFilter) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

type Config struct {
	ConfigMap            map[string]string `protobuf:"bytes,1,rep,name=configMap,proto3" json:"configMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_09fdc6f199145f27, []int{3}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetConfigMap() map[string]string {
	if m != nil {
		return m.ConfigMap
	}
	return nil
}

type Role struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoleType             RoleType `protobuf:"varint,2,opt,name=roleType,proto3,enum=customer.RoleType" json:"roleType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_09fdc6f199145f27, []int{4}
}

func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (m *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(m, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Role) GetRoleType() RoleType {
	if m != nil {
		return m.RoleType
	}
	return Role_worker
}

func init() {
	proto.RegisterEnum("customer.RoleType", RoleType_name, RoleType_value)
	proto.RegisterType((*CustomerRequest)(nil), "customer.CustomerRequest")
	proto.RegisterType((*CustomerRequest_Address)(nil), "customer.CustomerRequest.Address")
	proto.RegisterType((*CustomerResponse)(nil), "customer.CustomerResponse")
	proto.RegisterType((*CustomerFilter)(nil), "customer.CustomerFilter")
	proto.RegisterType((*Config)(nil), "customer.Config")
	proto.RegisterMapType((map[string]string)(nil), "customer.Config.ConfigMapEntry")
	proto.RegisterType((*Role)(nil), "customer.Role")
}

func init() { proto.RegisterFile("src/proto/customer.proto", fileDescriptor_09fdc6f199145f27) }

var fileDescriptor_09fdc6f199145f27 = []byte{
	// 478 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0xae, 0xd3, 0xdf, 0xcc, 0xa2, 0x10, 0xcc, 0x0a, 0x99, 0x5c, 0xb6, 0xe4, 0x54, 0x21, 0xd4,
	0xa2, 0x72, 0x41, 0xa8, 0x08, 0xa1, 0x0a, 0x56, 0x7b, 0xd8, 0x4b, 0xe0, 0x05, 0x42, 0x32, 0xbb,
	0xb5, 0x9a, 0xc6, 0xc6, 0x76, 0x59, 0x85, 0x3b, 0x27, 0x5e, 0x86, 0x07, 0xe2, 0x61, 0x90, 0x9d,
	0xa4, 0xed, 0x6e, 0xe9, 0x29, 0xf3, 0xcd, 0xf8, 0xf3, 0x7c, 0xf3, 0x8d, 0x03, 0x4c, 0xab, 0x6c,
	0x26, 0x95, 0x30, 0x62, 0x96, 0x6d, 0xb5, 0x11, 0x1b, 0x54, 0x53, 0x07, 0xe9, 0xa8, 0xc5, 0xf1,
	0x1f, 0x0f, 0x1e, 0x2f, 0x1b, 0x90, 0xe0, 0xf7, 0x2d, 0x6a, 0x43, 0x03, 0xf0, 0x78, 0xce, 0xc8,
	0x98, 0x4c, 0xfa, 0x89, 0xc7, 0x73, 0x4a, 0xa1, 0x57, 0xa6, 0x1b, 0x64, 0xde, 0x98, 0x4c, 0xfc,
	0xc4, 0xc5, 0xf4, 0x1c, 0xfa, 0xb8, 0x49, 0x79, 0xc1, 0xba, 0x2e, 0x59, 0x03, 0x9b, 0x95, 0x2b,
	0x51, 0x22, 0xeb, 0xd5, 0x59, 0x07, 0xe8, 0x07, 0xf0, 0xd3, 0x3c, 0x57, 0xa8, 0x35, 0x6a, 0xd6,
	0x1f, 0x77, 0x27, 0x67, 0xf3, 0x17, 0xd3, 0x9d, 0xa2, 0x07, 0xdd, 0xa7, 0x1f, 0xeb, 0xa3, 0xc9,
	0x9e, 0x13, 0xfd, 0x26, 0x30, 0x6c, 0xd2, 0xf4, 0x19, 0x0c, 0xb4, 0x51, 0x88, 0xc6, 0x09, 0xf4,
	0x93, 0x06, 0x59, 0x91, 0x19, 0x37, 0x55, 0x2b, 0xd2, 0xc6, 0x56, 0x8e, 0x36, 0xa9, 0xc1, 0x56,
	0xa4, 0x03, 0x34, 0x84, 0xee, 0x4f, 0x2e, 0x1b, 0x89, 0x36, 0xa4, 0xaf, 0xe0, 0x09, 0xd7, 0x5f,
	0x56, 0x5c, 0x4a, 0x5e, 0xde, 0x36, 0x8d, 0x58, 0x7f, 0x4c, 0x26, 0xa3, 0xe4, 0xb8, 0x10, 0x2f,
	0x20, 0xdc, 0x6b, 0xd6, 0x52, 0x94, 0x1a, 0x8f, 0x2c, 0x63, 0x30, 0xd4, 0xdb, 0x2c, 0xb3, 0xf7,
	0x78, 0xee, 0x9e, 0x16, 0xc6, 0x2f, 0x21, 0x68, 0xd9, 0x9f, 0x79, 0x61, 0x50, 0xd9, 0xb3, 0x6b,
	0xac, 0xee, 0x84, 0xca, 0x9b, 0x91, 0x5a, 0x18, 0xff, 0x22, 0x30, 0x58, 0x8a, 0xf2, 0x86, 0xdf,
	0xd2, 0xf7, 0xe0, 0x67, 0x2e, 0xba, 0x4e, 0x25, 0x23, 0xce, 0xc3, 0x8b, 0x03, 0x0f, 0x5d, 0xa9,
	0xf9, 0x5c, 0xa7, 0xf2, 0x53, 0x69, 0x54, 0x95, 0xec, 0x19, 0xd1, 0x02, 0x82, 0xfb, 0x45, 0xeb,
	0xc2, 0x1a, 0xab, 0xa6, 0xa3, 0x0d, 0xad, 0x5b, 0x3f, 0xd2, 0x62, 0xdb, 0xee, 0xb9, 0x06, 0xef,
	0xbc, 0xb7, 0x24, 0x5e, 0x41, 0x2f, 0x11, 0xc5, 0xe1, 0x94, 0xbe, 0x9b, 0x72, 0x06, 0x23, 0x25,
	0x0a, 0xfc, 0x5a, 0xc9, 0x9a, 0x14, 0xcc, 0x9f, 0xee, 0x35, 0x59, 0xc6, 0xd4, 0x54, 0x12, 0x93,
	0xdd, 0xa1, 0xf8, 0x02, 0x7a, 0x36, 0x43, 0x01, 0x06, 0x77, 0x42, 0xad, 0x51, 0x85, 0x1d, 0x7a,
	0x06, 0xc3, 0x4c, 0x94, 0x5a, 0x14, 0x18, 0x92, 0xf9, 0x5f, 0x02, 0xa3, 0xd6, 0x1e, 0x7a, 0x09,
	0x8f, 0x2e, 0xd1, 0xb4, 0x50, 0x53, 0x76, 0xfc, 0x68, 0x6a, 0x0b, 0xa3, 0xe7, 0x27, 0x9f, 0x53,
	0xdc, 0x79, 0x4d, 0xe8, 0x15, 0x04, 0x4b, 0x85, 0xa9, 0xc1, 0xdd, 0xd5, 0xa7, 0x09, 0x51, 0xf4,
	0xbf, 0x52, 0xbd, 0xe6, 0xb8, 0x43, 0x17, 0x70, 0x7e, 0xa8, 0xe9, 0xaa, 0x34, 0xa8, 0x6e, 0xd2,
	0x8c, 0x06, 0xf7, 0x07, 0x8f, 0xc2, 0x87, 0xcb, 0xb1, 0x42, 0xbe, 0x0d, 0xdc, 0xef, 0xf7, 0xe6,
	0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x07, 0xba, 0x1f, 0xba, 0x9a, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CustomerClient is the client API for Customer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomerClient interface {
	// Get all Customers with filter - A server-to-client streaming RPC.
	GetCustomers(ctx context.Context, in *CustomerFilter, opts ...grpc.CallOption) (Customer_GetCustomersClient, error)
	// Create a new Customer - A simple RPC
	CreateCustomer(ctx context.Context, in *CustomerRequest, opts ...grpc.CallOption) (*CustomerResponse, error)
	GetCustomersInterfac(ctx context.Context, in *Role, opts ...grpc.CallOption) (Customer_GetCustomersInterfacClient, error)
}

type customerClient struct {
	cc *grpc.ClientConn
}

func NewCustomerClient(cc *grpc.ClientConn) CustomerClient {
	return &customerClient{cc}
}

func (c *customerClient) GetCustomers(ctx context.Context, in *CustomerFilter, opts ...grpc.CallOption) (Customer_GetCustomersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Customer_serviceDesc.Streams[0], "/customer.Customer/GetCustomers", opts...)
	if err != nil {
		return nil, err
	}
	x := &customerGetCustomersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Customer_GetCustomersClient interface {
	Recv() (*CustomerRequest, error)
	grpc.ClientStream
}

type customerGetCustomersClient struct {
	grpc.ClientStream
}

func (x *customerGetCustomersClient) Recv() (*CustomerRequest, error) {
	m := new(CustomerRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *customerClient) CreateCustomer(ctx context.Context, in *CustomerRequest, opts ...grpc.CallOption) (*CustomerResponse, error) {
	out := new(CustomerResponse)
	err := c.cc.Invoke(ctx, "/customer.Customer/CreateCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) GetCustomersInterfac(ctx context.Context, in *Role, opts ...grpc.CallOption) (Customer_GetCustomersInterfacClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Customer_serviceDesc.Streams[1], "/customer.Customer/GetCustomersInterfac", opts...)
	if err != nil {
		return nil, err
	}
	x := &customerGetCustomersInterfacClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Customer_GetCustomersInterfacClient interface {
	Recv() (*Config, error)
	grpc.ClientStream
}

type customerGetCustomersInterfacClient struct {
	grpc.ClientStream
}

func (x *customerGetCustomersInterfacClient) Recv() (*Config, error) {
	m := new(Config)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CustomerServer is the server API for Customer service.
type CustomerServer interface {
	// Get all Customers with filter - A server-to-client streaming RPC.
	GetCustomers(*CustomerFilter, Customer_GetCustomersServer) error
	// Create a new Customer - A simple RPC
	CreateCustomer(context.Context, *CustomerRequest) (*CustomerResponse, error)
	GetCustomersInterfac(*Role, Customer_GetCustomersInterfacServer) error
}

func RegisterCustomerServer(s *grpc.Server, srv CustomerServer) {
	s.RegisterService(&_Customer_serviceDesc, srv)
}

func _Customer_GetCustomers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CustomerFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CustomerServer).GetCustomers(m, &customerGetCustomersServer{stream})
}

type Customer_GetCustomersServer interface {
	Send(*CustomerRequest) error
	grpc.ServerStream
}

type customerGetCustomersServer struct {
	grpc.ServerStream
}

func (x *customerGetCustomersServer) Send(m *CustomerRequest) error {
	return x.ServerStream.SendMsg(m)
}

func _Customer_CreateCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).CreateCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customer.Customer/CreateCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).CreateCustomer(ctx, req.(*CustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_GetCustomersInterfac_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Role)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CustomerServer).GetCustomersInterfac(m, &customerGetCustomersInterfacServer{stream})
}

type Customer_GetCustomersInterfacServer interface {
	Send(*Config) error
	grpc.ServerStream
}

type customerGetCustomersInterfacServer struct {
	grpc.ServerStream
}

func (x *customerGetCustomersInterfacServer) Send(m *Config) error {
	return x.ServerStream.SendMsg(m)
}

var _Customer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "customer.Customer",
	HandlerType: (*CustomerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCustomer",
			Handler:    _Customer_CreateCustomer_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetCustomers",
			Handler:       _Customer_GetCustomers_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetCustomersInterfac",
			Handler:       _Customer_GetCustomersInterfac_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "src/proto/customer.proto",
}
